//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rezervq
{
    using System;
    using System.Collections.Generic;
    
    public partial class cabinet
    {
        public int id { get; set; }
        public Nullable<int> nomercab { get; set; }
        public Nullable<int> id_fio { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> srok { get; set; }
        public Nullable<int> id_spec { get; set; }
    
        public virtual fio fio { get; set; }
        public virtual spec spec { get; set; }
    }
}
